import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export const getStaticProps = async () => {
  const token = process.env.API_TOKEN;
  const res = await fetch("http://194.95.193.79:1337/api/tests", {
    headers: new Headers({
      Authorization: `Bearer ${token}`,
    }),
  });
  const fetchedData = await res.json();

  return {
    props: {
      posts: fetchedData.data,
    },
  };
};

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/minff.jpg" width="100%" />
        <div className={styles.filter_container}>
          <span>Filter</span>
        </div>
        <div className={styles.card_container}>
          {posts.map((post) => (
            <Link href={"/" + post.id} key={post.id}>
              <div className={styles.posts}>
                <h3>{post.attributes.title}</h3>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
