import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link"

export const getStaticProps = async () => {
  const res = await fetch(
    "https://distracted-napier.185-243-11-121.plesk.page/wp-json/wp/v2/posts?"
  );
  const data = await res.json();

  return {
    props: {
      posts: data,
    },
  };
};

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Medieninformatik.de</h1>

        {posts.map((post) => (
          <Link href={'/' + post.id}  key={post.id}>
         <div className={styles.posts}>
              <h3>{post.title.rendered}</h3>
              </div>
          </Link>
        ))}
      </main>
    </div>
  );
}
