import Head from "next/head";
import Link from "next/link";
import ImageSlider from "../components/ImageSlider";
// export const getStaticProps = async () => {
//   const token =
//     "ef7b5769772f2edfc916bf362fab95267ebd3b3e3c730d86c81a72030b1e587d8cb192441dbda7079449e837a0d56ee95c6e030d8a4ea0519184f9e464409cb58a67d30197154b2cf5cf1003bfb713387b8ac631a93272fed98a80f333eb1d02b85ea6469fc0792b32db3b3a3525f4700da5f7229ef6215cd0c8a72ec7e5a20c";

//   try {
//     const res = await fetch(
//       "http://194.95.193.79:1337/api/blogeintrags?populate=*",
//       {
//         headers: new Headers({
//           Authorization: `Bearer ${token}`,
//         }),
//       }
//     );

//     const catres = await fetch(
//       "http://194.95.193.79:1337/api/categories?populate=*",
//       {
//         headers: new Headers({
//           Authorization: `Bearer ${token}`,
//         }),
//       }
//     );

//     const fetchedCats = await catres.json();
//     const fetchedData = await res.json();

//     return {
//       props: {
//         posts: fetchedData.data,
//         cats: fetchedCats.data,
//         error: false,
//       },
//       revalidate: 60,
//     };
//   } catch (e) {
//     console.error(e);
//     return {
//       props: {
//         cats: "Kategorien konnten nicht geladen werden.",
//         posts: "Beim Laden der Daten ist ein Fehler aufgetreten.",
//         error: true,
//       },
//     };
//   }
// };

// export default function Home({ posts, error, cats }) {
//   //console.log(cats);
//   if (!error) {
//     return (
//       <div className={styles.container}>
//         <Head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main className={styles.main}>
//           <ImageSlider
//             image1="/imageSlider/exma.png"
//             image2="/imageSlider/poster.png"
//             image3="/imageSlider/fextra.png"
//           />
//           <Category categories={cats} />

//           <div className={styles.card_container}>
//             {posts.map((post) => (
//               <Link href={"/" + post.id} key={post.id}>
//                 <BlogCard post={post} categories={cats} />
//               </Link>
//             ))}
//           </div>
//         </main>
//       </div>
//     );
//   }
//   //Hier wird der Fehlerfall abgefangen
//   else {
//     return (
//       <div className={styles.container}>
//         <Head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main className={styles.main}>
//           <span className={styles.error}>
//             Leider konnte keine Verbindung zur Datenbank aufgebaut werden...
//           </span>
//         </main>
//       </div>
//     );
//   }
// }

export const getStaticProps = async () => {
  const token =
    "1c893cea2289a8d28598469273a0966278e4d1f946893b772a8b1ace48cb4e4bf9c3e5da67dac5bd7ef4db17b1005fd87536c4543a1107769244ab41d613407868cc075265defd47e1160860c6ec853211df0dc935a5e3f29d76dacdfcf6f90fd1fdb7a9a76204586761639d6f557307b04f3de60e2a66f52d053a602ce4d32b";

  try {
    const res = await fetch("http://127.0.0.1:1337/api/tests", {
      headers: new Headers({
        Authorization: `Bearer ${token}`,
      }),
    });

    const fetchedData = await res.json();

    return {
      props: {
        posts: fetchedData.data,
        error: false,
      },
      revalidate: 60,
    };
  } catch (e) {
    console.error(e);

    return {
      props: {
        posts: "Beim Laden der Daten ist ein Fehler aufgetreten.",
        error: true,
      },
    };
  }
};

export default function Home({ posts, error }) {
  console.log(posts);
  if (!error) {
    return (
      <div>
        <Head>
          <title>Medieninformatik.de</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main></main>
      </div>
    );
  }
  //Hier wird der Fehlerfall abgefangen
  else {
    return (
      <div>
        <Head>
          <title>Medieninformatik.de</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <ImageSlider/>
          <span>
            Leider konnte keine Verbindung zur Datenbank aufgebaut werden...
          </span>
        </main>
      </div>
    );
  }
}
